name: Build Emergent Mobile App (APK)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  NODE_OPTIONS: "--max-old-space-size=4096"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # This tells GitHub to run all scripts inside the frontend folder!
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Android folder (Expo Prebuild)
        run: |
          npx expo prebuild --platform android --clean

      - name: Restrict Gradle Memory Usage
        run: |
          echo "org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m" >> android/gradle.properties
          echo "org.gradle.daemon=false" >> android/gradle.properties
          echo "org.gradle.parallel=false" >> android/gradle.properties

      - name: Build Android APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: INSIGHT-HR-App
          # Notice we added 'frontend/' to the start of this path
          path: frontend/android/app/build/outputs/apk/release/app-release.apk
